name: Tunilmu Deployment Actions

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker build --pull -t ${{ secrets.CI_REGISTRY_IMAGE }} .
        docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }}
        docker push "${{ secrets.CI_REGISTRY_IMAGE }}"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test || true

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          coverage/lcov.info
          test-report.xml

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker rm -f "tunilmu-fe" || true
          docker image rm -f ${{ secrets.CI_REGISTRY_IMAGE }} || true
          docker run --name "tunilmu-fe" -p 3000:3000 -d ${{ secrets.CI_REGISTRY_IMAGE }}
